[tool.flake8]
max_line_length = 120
max-doc-length = 120
exclude = "test_*.py"
select = ["E", "F", "W"]
ignore = ['F401']


[tool.pytest.ini_options]
timeout = 60
minversion = "6.0"
python_files = "test_*.py"
addopts = "-p no:requests_mock"
testpaths = [
    "tests",
    ".tmp"
]


[tool.mypy]
no_incremental = true
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_any_generics = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
allow_untyped_decorators = true
exclude = [
    "tests/",
    ".tmp/",
    ".venv/"
]
